<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MacMini01.local" name="Test1" tests="27" failures="5" timestamp="27 Jun 2017 11:11:00 GMT" time="635.609" errors="0">
  <testcase name="LoginpageURLVerification" time="0.37" classname="com.s3.TestCasesPhase2.Login.Test_Login_LoginPageURL"/>
  <testcase name="LoginpageURLVerification" time="0.226" classname="com.s3.TestCasesPhase2.Login.Test_Login_LoginPageURL">
    <failure type="java.lang.AssertionError" message="expected [Pass] but found [Fail]">
      <![CDATA[java.lang.AssertionError: expected [Pass] but found [Fail]
	at com.s3.TestCasesPhase2.Login.Test_Login_LoginPageURL.LoginpageURLVerification(Test_Login_LoginPageURL.java:50)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginpageURLVerification -->
  <testcase name="LoginPageVerification" time="1.525" classname="com.s3.TestCasesPhase2.Login.Test_Login_LoginPageElementVerification"/>
  <testcase name="LoginErrorMessage" time="1.541" classname="com.s3.TestCasesPhase2.Login.Test_Login_LoginBlank"/>
  <testcase name="LoginErrorMessage" time="1.528" classname="com.s3.TestCasesPhase2.Login.Test_Login_LoginBlank">
    <failure type="java.lang.AssertionError" message="expected [Pass] but found [Fail]">
      <![CDATA[java.lang.AssertionError: expected [Pass] but found [Fail]
	at com.s3.TestCasesPhase2.Login.Test_Login_LoginBlank.LoginErrorMessage(Test_Login_LoginBlank.java:54)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorMessage -->
  <testcase name="LoginErrorMessage" time="1.537" classname="com.s3.TestCasesPhase2.Login.Test_Login_LoginBlank"/>
  <testcase name="LoginErrorMessage" time="3.998" classname="com.s3.TestCasesPhase2.Login.Test_Login_InvalidLogin"/>
  <testcase name="LoginErrorMessage" time="3.931" classname="com.s3.TestCasesPhase2.Login.Test_Login_InvalidLogin"/>
  <testcase name="LoginErrorMessage" time="3.965" classname="com.s3.TestCasesPhase2.Login.Test_Login_InvalidLogin"/>
  <testcase name="LoginTest" time="6.956" classname="com.s3.TestCasesPhase2.Login.Test_Login_ValidLogin"/>
  <testcase name="LoginTest" time="31.688" classname="com.s3.TestCasesPhase2.Login.Test_Login_ValidLogin">
    <failure type="java.lang.AssertionError" message="expected [Pass] but found [Fail]">
      <![CDATA[java.lang.AssertionError: expected [Pass] but found [Fail]
	at com.s3.TestCasesPhase2.Login.Test_Login_ValidLogin.LoginTest(Test_Login_ValidLogin.java:52)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase name="LoginTest" time="7.644" classname="com.s3.TestCasesPhase2.Login.Test_Login_ValidLogin"/>
  <testcase name="LoginErrorMessage" time="6.787" classname="com.s3.TestCasesPhase2.Login.Test_Login_Logout"/>
  <testcase name="LoginErrorMessage" time="33.684" classname="com.s3.TestCasesPhase2.Login.Test_Login_Logout">
    <failure type="java.lang.AssertionError" message="expected [NA] but found [Pass]">
      <![CDATA[java.lang.AssertionError: expected [NA] but found [Pass]
	at com.s3.TestCasesPhase2.Login.Test_Login_Logout.LoginErrorMessage(Test_Login_Logout.java:65)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorMessage -->
  <testcase name="LoginErrorMessage" time="1.145" classname="com.s3.TestCasesPhase2.Login.Test_Login_ForgotPassword_UI"/>
  <testcase name="LoginErrorMessage" time="2.441" classname="com.s3.TestCasesPhase2.Login.Test_Login_ForgotPassword"/>
  <testcase name="LoginErrorMessage" time="2.311" classname="com.s3.TestCasesPhase2.Login.Test_Login_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [Pass] but found [Fail]">
      <![CDATA[java.lang.AssertionError: expected [Pass] but found [Fail]
	at com.s3.TestCasesPhase2.Login.Test_Login_ForgotPassword.LoginErrorMessage(Test_Login_ForgotPassword.java:53)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorMessage -->
  <testcase name="LoginErrorMessage" time="30.693" classname="com.s3.TestCasesPhase2.Login.Test_Login_ForgotPasswordDismiss"/>
  <testcase name="LoginTest" time="39.082" classname="com.s3.TestCasesPhase2.Login.Test_Login_Roles"/>
  <testcase name="LoginTest" time="30.424" classname="com.s3.TestCasesPhase2.Login.Test_Login_Roles"/>
  <testcase name="LoginTest" time="20.684" classname="com.s3.TestCasesPhase2.Login.Test_Login_Roles"/>
  <testcase name="LoginTest" time="38.109" classname="com.s3.TestCasesPhase2.Login.Test_Login_Roles"/>
  <testcase name="LoginTest" time="70.981" classname="com.s3.TestCasesPhase2.Login.Test_Login_Roles"/>
  <testcase name="TestRememberme" time="22.265" classname="com.s3.TestCasesPhase2.Login.Test_login_RememberMe"/>
  <testcase name="TestRememberme" time="17.503" classname="com.s3.TestCasesPhase2.Login.Test_login_RememberMe"/>
  <testcase name="TestRememberme" time="35.512" classname="com.s3.TestCasesPhase2.Login.Test_login_RememberMe"/>
  <testcase name="TestRememberme" time="21.318" classname="com.s3.TestCasesPhase2.Login.Test_login_RememberMe"/>
</testsuite> <!-- Test1 -->
